AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 Instance creation'
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-09538990a0c4fe9be
      InstanceType: t2.micro
      KeyName: aws-devops
      Tags:
        - Key: "Name"
          Value: "EC2-Practice"
        - Key: "Course"
          Value: "DevOps"